### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by nrbnlulu** [petroly-initiative/petroly-django#78] opened 2022-07-12 19:01 UTC
Hey @ammar-faifi I was checking out your website and encountered this issue:
[Screencast from 12-07-22 21:55:10.webm](https://user-images.githubusercontent.com/88795475/178573102-45ea194e-dd2b-493c-bdd6-cbeb7397e0ea.webm)

**Comment by ammar-faifi** [comment] 2022-07-13 07:28
dude you are legend, I've never thought you would try it out 😁

Yes, it is an issue from the `register` query it still has the old syntax of `graphene` auth.
pls pull last commits from https://github.com/petroly-initiative/petroly-react repo


the confirmation link received by email will start with `https://www.petroly.co/.......`
so you need to replace that domain with the `localhost:3000`

thank u again

**Comment by nrbnlulu** [comment] 2022-07-15 15:13
Your site looks pretty good though :100: .  

> Yes, it is an issue from the register query it still has the old syntax of graphene auth.  

I did not understood, is it an issue in strawberry-django-auth? 

> and I also it you on localhost , to the confirmation link received by email starts with https://www.petroly.co/.......  

didn't understood either :upside_down_face:

**Comment by ammar-faifi** [comment] 2022-07-15 16:11
> I did not understood, is it an issue in strawberry-django-auth?

I meant that we used `graphene-django-auth` initially, but after moving to `strawberry-django-auth` we update the file https://github.com/petroly-initiative/petroly-react/blob/main/api/mutations.js.  this file is a list of mutations to be used in the front end. so the issue is just we forgot to update the `register` mutation to match strawberry-django-auth`.

>didn't understood either 🙃

sorry, I didn't realize they're so much typos, I update the original comment.

**Closed as completed** 2022-07-19 15:18 UTC
Labels: bug
